project:
  type: website

website:
  title: "NonCoder"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Pyramid.qmd
        text: Blogs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

