---
title: "Pyramid in Python"
format: html
editor: visual
---

## Introduction

Printing a pyramid is a very basic exercise after learning `Loop` in any programming language.And probably the most challenging one is Pascal Pyramid.

::: columns
::: {.column width="50%"}
```{python}
#| echo: false
def pyramid(n):
  for i in range(n,0,-1):
    print(" "*(i-1)+" *"*(n-i))
pyramid(7)

```
:::

::: {.column width="50%"}
```{python}
#| echo: false
def pyramid(n):
  for i in range(n,0,-1):
    print(" "*(i-1)+f" {n-i}"*(n-i))
pyramid(7)
```
:::
:::

In this vlog ,we will be discussing about how we can make one such using just 4 lines of code.

## Let's Begin

Python is a Low-level programming language.It has many easy or rather user-friendly way of handling strings where as in `C`-Language its not so obvious.So lets come to the topic.

In `Python` one can add or multiply strings.Like,

```{python}
"*"*4+"+"
```

You can also print "Nothing"(!) in `Python`

```{python}
"  *"   #---Printing two space followed by a star
```

## Building Pyramid

Let's look into the pyramid again.

```{python}
#| echo: false
def pyramid(n):
  for i in range(n,0,-1):
    print(" "*(i-1)+" *"*(n-i))
pyramid(5)

```

Now without looking at `*` ,try to look into the string `*`,a space followed by star.Bang!!!

-   **Steps**

1.  Print `n-1` many gaps and `*`.

2.  Print `n-2` many gaps and two times `*` and so on.

## So the final code

```{python}
def pyramid(n):
  for i in range(n,0,-1):
    print(" "*(i-1)+" *"*(n-i))
pyramid(5)

```
